### ISSUE TITLE
Clarification of actual and planned date relationships

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Extra-Documentation#331]
At the moment, [`activity-date` rules](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/activity-date/#rules) include restrictions between `start-actual` and `end-actual` / `start-planned` and `end-planned`. There are not, however, any restrictions (Rules or [Guidelines](http://iatistandard.org/202/activity-standard/overview/dates/#considerations)) between actual and planned values - for example, requiring that `end-planned` is after `start-actual`.

It is not immediately clear whether there should be any restriction on ordering (it seems reasonable that there is not, so as to demonstrate factors such as over-running projects), or whether both may exist together (akin to an issue with [original and revised budgets](https://discuss.iatistandard.org/t/clarifying-the-relationship-between-original-budget-and-revised-budget-in-iati-activities/819)).

**Comment by andylolz** [comment]
> There are not, however, any restrictions (Rules or [Guidelines](http://iatistandard.org/202/activity-standard/overview/dates/#considerations)) between actual and planned values - for example, requiring that `end-planned` is after `start-actual`.

I’m pretty sure there’s no relationship between planned dates and actual dates. Typically, `start-actual` will occur before `end-planned`, but it might not, and there certainly shouldn’t be a requirement for it to.

I guess it could be stated explicitly that there’s no relationship between planned and actual dates… Perhaps it’s useful, but I’m not really sure it’s necessary. In the absence of it being stated explicitly, I certainly wouldn’t assume otherwise.

**Comment by amy-silcock** [comment]
My understanding is that there is no relationship between planned and actual dates. I agree with @andylolz  that stating the explicitly is not necessary
