### ISSUE TITLE
SDG Guidance Page : link

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Extra-Documentation#566]

**Comment by samuele-mattiuzzo** [comment]
```
Changelog
~~~~~~~~~

| This blurb is valid for *a document in v2.x*: `this is a link  <http://this.links.somewhere>`__
```

**Comment by andylolz** [comment]
@amy-silcock why is this new SDG guidance in an externally hosted PDF, rather than putting the guidance inline, in HTML? Is there a plan to convert it to HTML?

Inline HTML is good, because (via git commit messages) it’s possible to tell when and why changes were made. So it’s more transparent. It’s also better for site search and things like that.

I ask because I don’t think there are other instances of guidance pages linking to external PDFs, so I worry this could set a precedent of making guidance less transparent.

**Comment by amy-silcock** [comment]
Hi @andylolz, as you know we're in the process of moving the reference site onto the new IATI Standard website. At the same time we've been working on a number of different guidance areas. The re-worked overview pages will be online later today.

Some of the guidance is ready before the move to the new website and we don't want to delay it being accessible.
 
So for the time being, we're putting the new guidance up as pdf docs, and will be linking it to existing pages. Then when we're ready to move everything to the new website, the new and revised guidance will be shown on each page.

**Comment by samuele-mattiuzzo** [comment]
Closing because this is deployed live already

**Comment by andylolz** [comment]
> when we're ready to move everything to the new website, the new and revised guidance will be shown on each page.

That’s great to hear – thanks @amy-silcock.

Since the reference site will continue to be built from source, I guess it wouldn’t be wasted work to convert the PDFs to HTML? What I mean is, I guess that conversion isn’t blocked by the reference site move, which I guess won’t happen for a while yet.

**Comment by samuele-mattiuzzo** [comment]
Correct, they are not related, but the key here is that not all the new content for the pages is ready. The HTML will happen in bulk when all are ready. Whether that coincides with the Reference site move or not is irrelevant.

**Comment by andylolz** [comment]
Ahh, okay I see. Thanks for clarifying.

So (just to restate for my own benefit) reference site move is irrelevant. New guidance will be converted from PDF in bulk once it’s all ready.
