### ISSUE TITLE
planned-disbursement

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Extra-Documentation#93]
Aware that this has `period-start` & `period-end` elements, but IATI only expects a single date

This is not reflected here:

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/planned-disbursement/

Aware that this is within 2.01 discussions (http://support.iatistandard.org/entries/22915067-Modify-planned-disbursement-period-start-Alter-guidance-AND-make-start-date-mandatory) but wanted to check if we should make any 1.04 documentation changes - @bill-anderson

**Comment by bill-anderson** [comment]
cf my slide from montreal on planned-disb
- A further breakdown of the budget providing predictability of actual cash flow
- Particularly important for budget support
- Also useful for grant funding that has highly predictable disbursement dates
- (Problem in standard in accurately reporting a single date rather than a period – to be fixed in 1.05)

Can we change guidance in 1.04 to say you can either report a single date or a period (but NB that this refers to an actual planned cash transfer, not a budget)

**Comment by stevieflow** [comment]
@Bjwebb is this a ruleset change?

Putting into post-1.04 right now

**Comment by Bjwebb** [comment]
The 2.01 changes require rulesets, but Bill's suggestions for 1.04/1.05 are changes to pieces of human readable text.

**Comment by stevieflow** [comment]
In terms of code-examples, I just need to confirm whether our best practice would be to:

a) keep as is (where period-start = period-end): http://iatistandard.org/activity-standard/iati-activities/iati-activity/planned-disbursement/
b) provide a second example whereby there is a date range
c) add example with _only_ `period-start`
d) add text to explain the above

@Bjwebb is option c) invalid?

@bill-anderson what is preferred in 1.04?

**Comment by bill-anderson** [comment]
I don't like period-start = period-end
I favour doing b) and c)

**Comment by Bjwebb** [comment]
Option c) is not invalid against the schema, no.

**Comment by stevieflow** [comment]
@bill-anderson ok, will do

@Bjwebb wat?  Do you mean option c is valid against the schema ?

**Comment by Bjwebb** [comment]
Yes, option c is valid against the schema. Since we do not enforce ordering, it could not possibly be invalid against the schema, even if it was incorrect.

**Comment by stevieflow** [comment]
I've changed the code example as per discussion.

Have also added a text to describe the date, as per #87
